postalsys/emailengine

- lib/tools.js
- workers/api.js
@andris9 This is related to https://github.com/andris9/imapapi/issues/10
outlook.com's OAuth access tokens are lengthy
> Increase accessToken length

- lib/connection.js
- lib/mailbox.js
- package.json
- workers/api.js
I need to add three parameters to account in my project.
I think it will be very usefull for others too.
**copy (boolean)**- this parameter tells if submitted messages via API should be copied to Sent folder. Office365 works the same way as Gmail and automatically creates message in IMAP folder. Without this parameter we have duplicates in IMAP folders.
**notifyFrom (iso date)** - this parameter tells what messages should be notified via webhook during initial account synchronization.
**resyncDelay (number)**- this parameter tells how often in seconds full synchronization should run. Now this parameter is hardcoded to 15 min.
example json:
{
"account": "imapapi@xyz.com",
"name": "Test M365",
"copy": false,
"notifyFrom": "2020-09-01T00:00:00Z",
"resyncDelay": 60,
"imap": {
"host": …
> New account parameters: copy, notifyFrom and resyncDelay

- views/layout/app.hbs
Hi,
This is a very minor fix to correct the misspelling of the word 'authentication':
Thanks.
> Fix misspelling of authentication

- lib/routes-ui.js
- views/accounts/register/index.hbs
- views/config/oauth.hbs
- views/config/service.hbs
- workers/api.js
- Added option to the labs section to enable OAuth2 for Mail.ru. It is not enabled by default due to insufficient testing.
> Added option to enable support for mail.ru OAuth2

- .github/workflows/deploy.yml
- lib/db.js
- lib/get-secret.js
- lib/routes-ui.js
- lib/tools.js
- package.json
- scan.js
- server.js
- workers/api.js
- workers/documents.js
- workers/imap.js
- workers/smtp.js
- workers/submit.js
- workers/webhooks.js
* If environment variable `KEY` is not set but there is `KEY_FILE` then try to read the value from the referenced path as the value for that environment key
```
$ echo 'secretpass' > /path/to/secret.txt
$ export EENGINE_SECRET_FILE=/path/to/secret.txt
$ emailengine
```
> Allow reading ENV values from files with key_FILE=path

- .github/workflows/deploy.yml
- lib/connection.js
- lib/consts.js
When downloading attachments, EmailEngine uses chunking instead of downloading the entire attachment in a single call. If the latency between the EmailEngine instance and IMAP server is high, then this chunking approach adds considerable overhead to the download speed, as each chunk requires an additional IMAP command to be sent.
This PR adds the option to increase the default chunk size and thus increase the download speed.
```
EENGINE_CHUNK_SIZE=65536
```
> Alow to set attachment chunk size with ENV value

- lib/tools.js
- package.json
* replace md5 with murmurhash
murmurhash is about 4 times faster than md5 for the use case that EmailEngine uses it (calculating rendezvous scores)
> Use murmurhash instead of md5 for distribution hashes

- lib/routes-ui.js
When navigating to `/admin/login` without the `next` query argument, then login always failed as the authentication validator detected an empty string value for `next`. This PR fixes this by removing empty `next` values from the schema validation
> Do not reject authentication when 'next' is an empty string

- lib/imapproxy/imap-server.js
- lib/tools.js
- package.json
- translations/messages.pot
- workers/api.js
- workers/smtp.js
* Allow creating user tokens with `imap-proxy` scope
* Allow using CIDR ranges for IP restrictions
* Show correct authfail error for IMAP proxy failing authentication requests
> Fix IP restriction handling for IMAP proxy

- bin/emailengine.js
EmailEngine CLI commands for issuing tokens, exporting licenses, etc included a trailing newline that, in some cases, when using that output in scripts, caused issues with unexpected newlines.
> Fix CLI trailing newlines

- lib/connection.js
- lib/db.js
- package.json
- workers/imap.js
Make sure an email is stored in ElasticSearch first before sending out a webhook
> Process DocumentStore entry before sending a webhook

- .github/workflows/deploy.yml
- lib/consts.js
- lib/tools.js
- workers/api.js
Added new ENV variables
* `EENGINE_CORS_ORIGIN`: a space separated list of allowed origins
* `EENGINE_CORS_MAX_AGE` CORS max age value (can use duration values like `2h` or `60s`)
The mappgin CLI arguments are the following
* `--cors.origin`: allowed origin value. Can be specified multiple times for different origins
* `--cors.maxAge` CORS max age value (can use duration values like `2h` or `60s`)
```
$ emailengine --cors.origin="http://127.0.0.1:3000" --cors.maxAge=2h
```
> Added support for CORS

- workers/webhooks.js
Do not delete text info from webhooks when textNotify is disabled. Instead, only clear text content, if needed.
> Do not delete text info from webhooks

- lib/connection.js
- views/dashboard.hbs
- workers/api.js
* `mailMerge` structure accepts new propety `sendAt` that will override the message level `sendAt` value
* Fixed a bug with mail merge and message level `sendAt` processing
* Trigger request against swagger.json on server startup to trigger caching
> Allow setting mail merge specific send at values

- .github/workflows/deploy.yml
- views/accounts/account.hbs
- workers/api.js
* Oauth2 account email overrides the email address provided as the account address for the authentication form
* Fixed a minor bug with default type for `/v1/authentication/form`
* Show a confirmation when clicking on the "renew grant" button
* Do not show a dropdown for delivery tests when there are not registered SMTP gateways
> Prefer account email address when setting up OAuth2 accounts

- lib/connection.js
* Include messageId in messageDeliveryError webhook
```
{
"time": "2022-09-14T17:07:36+02:00",
"remote_addr": "90.191.152.39",
"content_type": "application/json",
"request": {
"serviceUrl": "http://127.0.0.1:3000",
"account": "example",
"date": "2022-09-14T15:07:35.832Z",
"event": "messageDeliveryError",
"data": {
"queueId": "1833c8a88a86109a1bf",
"envelope": {
"from": "andris@ekiri.ee",
"to": [
"andris@ethereal.email"
]
},
"messageId": "<29e26263-7125-ff56-4f80-83a5cf737d5e@ekiri.ee>",
"error": "400 Message Not Accepted",
"errorCode": "EPROTOCOL",
"smtpResponseCode": 400,
"job": {
"attemptsMade": 1,
"attempts": 10,
"nextAttempt": "2022-09-14T15:07:45.465Z"
}
}
}
}
```
> Include messageId in messageDeliveryError webhook

- .github/workflows/deploy.yml
- lib/arf-detect.js
- lib/consts.js
- lib/mailbox.js
* Whenever a complaint is detected (usually an ARF report), then EmailEngine emits a webhook `messageComplaint`
> Added new webhook type - messageComplaint

- lib/mailbox.js
- workers/api.js
Added new query argument to message information requests `embedAttachedImages`.
It allows to automatically fetch attached images and embed these as data URIs
```
curl "http://127.0.0.1:7003/v1/account/example/message/AAAAAQAABvg?textType=*&embedAttachedImages=true"
```
> Allow to automatically fetch attached images and embed these as data URIs

- lib/account.js
- lib/connection.js
- lib/mailbox.js
- lib/routes-ui.js
- lib/schemas.js
- lib/tools.js
- workers/api.js
* new account setup option `syncFrom` (date value). If not set, then EmailEngine will sync only these emails to ES that have internal date newer than `syncFrom` value
> Added option syncFrom to limit message syncing to ElasticSearch

- lib/es.js
EmailEngine v2.26.9
Node.js v16.17.1
Redis v7.0.5
ImapFlow v1.0.110
ELK v4.2.0
1. Create new clear instance of EmailEngine
2. Enable DocumentStore
3. Add new email account
4. Check ES logs
There will be ``MapperParsingException`` with message ``Failed to parse mapping: unknown parameter [enabled] on mapper [preview] of type [text]``
I've replaced ``enabled`` with ``index``, because ``enabled`` can apply only to objects and ``index`` applies to all other data types
[Current ES docs - Mapping - Index](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-index.html)
[Current ES docs - Mapping - Enabled](https://www.elastic.co/guide/en/elasticsearch/reference/current/enabled.html)
> fix ES mapper parsing exception with unknown [enabled] parameter

- package.json
- workers/smtp.js
If TLS for SMTP is disabled, remove STARTTLS option
> If TLS for SMTP is disabled, remove STARTTLS option

- workers/api.js
* Allow configuring max HTTP request body size for message uploads
* Added new env variable `EENGINE_MAX_BODY_SIZE` (defaults to `50M`)
* Added new cli option `--api.maxBodySize=50M`
> Configure max body size

- .github/workflows/deploy.yml
- lib/connection.js
- lib/routes-ui.js
- views/config/document-store.hbs
- views/config/service.hbs
- views/partials/side_menu.hbs
- workers/api.js
- workers/documents.js
* If a mailbox folder is deleted, remove entries from Document Store
* If an account is deleted, clear account entries from the threads index
* Remove the beta label from Document Store settings
> Fix deleted folder handling for Document Store

- lib/account.js
Do not throw when listing messages from a missing mailbox folder
> Do not throw when listing messages from a missing mailbox folder

- .github/workflows/deploy.yml
- lib/connection.js
- package.json
If message-id is changed by the SMTP server, and the client is informed about it, then use the updated value as `messageId` in webhooks, and `originalMessageId` for the original value
> Hotmail message ID

- lib/db.js
Changed Redis reconnect backoff to delay at least 1 second. See https://github.com/luin/ioredis/issues/1718
New retry times are 1, 1, 2, 4, 8, 14, 15, ...15 seconds
> Changed Redis reconnect backoff to delay at least 1 second

- lib/connection.js
Do not throw if referenced email does not have any flags set
> Do not throw if referenced email does not have any flags set

- lib/account.js
- lib/connection.js
- lib/consts.js
- lib/routes-ui.js
- lib/subconnection.js
- server.js
- views/accounts/account.hbs
- workers/api.js
- workers/imap.js
Allow creating "probe" IMAP connections that notify the primary connection for changes on monitored secondary mailbox folders
> Added support for subconnections to monitor changes on secondary mailboxes

- lib/mailbox.js
- lib/webhooks.js
Added data.messageSpecialUse property to messageNew webhooks.
This allows easier categorizing of emails (`\Inbox` vs `\Sent`) as the folder might be `\All` for both
> Added data.messageSpecialUse property to messageNew webhooks

- lib/schemas.js
- package.json
Increase UID and sequence search length limit from 256B to 8kB
> Increase UID and sequence search length limit from 256B to 8kB

- workers/api.js
Make sure that account id defaults to null to prevent error response if account id is not set
> Make sure that account id defaults to null

- lib/account.js
Make sure that preview property is filtered out when requesting message details from ElasticSearch
> Remove preview property from message details

- README.md
I was looking for a way to get a [prepared access token](https://emailengine.app/prepared-access-token) while using EmailEngine as a Docker Container without installing EmailEngine directly on my system. As this approach is not documented anywhere, I decided to give a step-by-step instruction on how to achieve this by executing `emailengine` commands without the CLI. 
If you are okay with the changes, you might want to consider adding this to your [Docker documentation](https://emailengine.app/docker) as well.
> Added instruction on how to execute CLI commands while using the Docker Container.

- lib/autodetect-imap-settings.js
T-Online is a large german E-Mail provider which requires an App Password for Authentication.
I added it to the list so Instructions are shown in the Form.
> Add T-Online to providers needing an app password
