postalsys/emailengine

systemd/imapapi

Hey Andris,
Firstly, Thanks for your work on IMAP API.
I'd like to contribute an example systemd unit file so it becomes a bit easier for new IMAP API users, especially those who haven't hosted a Node JS app before (like me), to host IMAP API.

Example systemd unit file

---

README.md

Fixed port in docs

---

bin/emailengine.js
server.js

- Fixed unref upgradeCheckTimer
- Renamed rename variable CHECK_UPGRADE_TIMEOUT to UPGRADE_CHECK_TIMEOUT
- Fixed help command typo
- Fixed typo in variable name

A few misc fixes

---

static/front/index.html
views/config/webhooks.hbs
workers/webhooks.js

- Only auto-unsubscribe webhooks if server returned 410

Only auto-unsubscribe webhooks if server returned 410

---

lib/account.js
lib/consts.js
lib/redis-scan-delete.js
package.json

* Use Redis command SCAN instead of KEYS

Use Redis command SCAN instead of KEYS

---

lib/routes-ui.js
package.json

Bumped deps

---

lib/encrypt.js
lib/routes-ui.js
views/gateways/edit.hbs
views/partials/gateway_form.hbs

Fixed listing gateways with encrypted passwords

Fixed listing gateways with encrypted passwords

---

.github/workflows/deploy.yml
lib/es.js
lib/mailbox.js
lib/routes-ui.js
lib/schemas.js
views/config/service.hbs

* Resolve category for incoming Gmail emails

Resolve category for incoming Gmail emails

---

lib/account.js
lib/lua/s-list-accounts.lua
lib/routes-ui.js
translations/messages.pot
views/accounts/index.hbs
views/layout/app.hbs
workers/api.js

* Filter accounts by string match in the web UI
* Filter accounts by string match in the account listing API endpoint with `query` argument

Search accounts by string match

---

lib/consts.js
server.js
workers/webhooks.js

* New webhook `accountAdded`
* * New webhook `accountDeleted`

Added webhooks accountAdded, accountDeleted

---

.eslintrc
.github/workflows/deploy.yml
lib/connection.js
lib/routes-ui.js
views/accounts/account.hbs
views/config/service.hbs
views/partials/test_send.hbs
workers/api.js

Added a feature to test email delivery for an account
Tests SPF, DKIM, and DMARC

Email delivery testing

---

lib/connection.js
lib/get-raw-email.js
lib/routes-ui.js
lib/schemas.js
translations/messages.pot
views/partials/template_form.hbs
views/templates/template.hbs
workers/api.js

* Added new email submission and template property `previewText`

Added new email sending property previewText

---

lib/connection.js

Also, if IMAP can not be accessed

Reject forward/reply calls if references message is not found

---

lib/es.js
lib/generate-text-preview.js
package.json
workers/documents.js

Generate an unindexed preview text field for documents stored in ElasticSearch

Added preview fields for stored ElasticSearch documents

---

lib/schemas.js
workers/api.js
workers/documents.js

Generate an unindexed preview text field for documents stored in ElasticSearch

Feature es preview

---

lib/connection.js
package.json
server.js
workers/api.js
workers/imap.js

* Fixed `reference.ignoreMissing` option for document store

Fixed reference.ignoreMissing option for document store

---

lib/connection.js
lib/consts.js

* Set default download chunk size to 1MB
* Allow using size values (1MB, 1kB etc) as values for `EENGINE_CHUNK_SIZE`

Set default download chunk size to 1MB

---

lib/account.js
lib/connection.js
lib/mailbox.js
lib/schemas.js
package.json
server.js
workers/api.js
workers/documents.js
workers/imap.js

This PR makes it possible to update/delete/move messages based on a search query instead of running a separate command against every message.

Feature: mass message actions

---

.github/workflows/deploy.yml
views/dashboard.hbs
workers/api.js

Cache Swagger definition file

---

docker-compose.yml
static/front/index.html
static/index.html
views/account/login.hbs
views/config/license.hbs
views/config/oauth.hbs
views/config/service.hbs
views/config/smtp.hbs
views/dashboard.hbs
views/gateways/index.hbs
views/partials/add_account_modal.hbs
views/templates/index.hbs
views/tokens/index.hbs
views/upgrade.hbs

* Use 'no-referrer' policy for outgoing links

Use 'no-referrer' policy for outgoing links

---

lib/account.js
lib/connection.js
lib/consts.js
lib/db.js
lib/lua/h-incrby-exists.lua

* After first successful sync, emit `accountInitialized` webhook

Emit accountInitialized webhook after first sync

---

lib/autodetect-imap-settings.js

Autodiscovery for custom domains hosted by Zoho

Autodiscovery for custom domains hosted by Zoho

---

.github/workflows/deploy.yml
lib/routes-ui.js
lib/webhooks.js
static/css/app.css
views/webhooks/index.hbs
views/webhooks/webhook.hbs

* Log and display execution errors for webhook routing functions

Webhook exec errors

---

lib/mailbox.js
lib/webhooks.js
workers/webhooks.js

Do not throw on unitialized notifyHeaders setting

Do not throw on unitialized notifyHeaders setting

---

lib/account.js
lib/connection.js
lib/imapproxy/imap-server.js
package.json
server.js
workers/api.js
workers/imap.js
workers/smtp.js
workers/submit.js

If a sending command fails, try to detect if the SMTP transaction finished, and if it did, do not fail the entire job.

Improve sending robustness

---

workers/api.js

Added delivery test API routes

Added delivery test API routes

---

lib/connection.js
lib/consts.js
lib/db.js
lib/lua/ee-list-add.lua
lib/lua/ee-list-remove.lua
lib/routes-ui.js
server.js
views/unsubscribe.hbs
workers/api.js

When using Mail-Merge:
* allow specifying a list Id
* If list-id is set, then allow setting an unsubscribe address
* Recipients can unsubscribe (and if it was a mistake, to re-subscribe)
* API methods to add and remove addresses from blocklists

Unsubscribe and block features

---

workers/api.js

* Added API endpoint to stream account state changes

Added API endpoint to stream account state changes

---

lib/append-list.js
workers/imap.js

msgpack exploded if error object included a circular ref

msgpack exploded if error object included a circular ref

---

.github/workflows/deploy.yml
package.json

Bumped pubface library to fix network scan

---

lib/routes-ui.js
lib/tools.js
package.json
server.js
views/dashboard.hbs

Updated dasboard elements list

Updated dasboard elements list

---

lib/account.js
lib/connection.js
server.js
workers/api.js
workers/imap.js

* Added method to RENAME a mailbox

Added method to RENAME a mailbox

---

lib/connection.js

Fixes 500 errors for mailbox create and rename

Fixed error responses for mailbox rename and create

---

lib/account.js
server.js
workers/imap.js

Return an error if mailbox listing was not completely processed

Return an error if mailbox listing was not completely processed

---

lib/connection.js
lib/mailbox.js
workers/webhooks.js

Only process document store messages where `syncFrom` is older than the message date

Only process too old document store messages

---

lib/connection.js

Fix missing ES events

---

lib/routes-ui.js
lib/schemas.js
views/config/webhooks.hbs
views/partials/webhook_form.hbs
views/partials/webhooks_editor_functions.hbs
workers/webhooks.js

Added support for custom webhook request headers

Added support for custom webhook request headers

---

lib/routes-ui.js

Do not fail validation if state for account search is an empty string

Do not fail validation if state for account search is an empty string

---

.github/workflows/deploy.yml
lib/routes-ui.js
workers/api.js

* Updated delivery test email message

Delivery test

---

lib/imapproxy/imap-server.js

Log proxied IMAP connections only if the raw logger option is enabled

Log proxied IMAP connections only if the raw logger option is enabled

---

lib/connection.js

* Add `$Forwarded` flag to forwarded emails

Add $Forwarded flag to forwarded emails

---

.github/workflows/discord.yml
lib/connection.js
workers/api.js

Added baseUrl property for message submissions

Added baseUrl property for message submissions

---

lib/routes-ui.js
workers/api.js
workers/webhooks.js

Clear webhook error flag if webhooks are disabled

Clear webhook error flag if webhooks are disabled

---

lib/routes-ui.js
lib/tokens.js
views/accounts/account.hbs
views/tokens/index.hbs
views/tokens/new.hbs
workers/api.js

Added Web UI for listing account tokens

Added Web UI for listing account tokens

---

lib/schemas.js
workers/api.js

Fix broken 'oauth2.authorize=true' request

Fix broken 'oauth2.authorize=true' request

---

package.json

Fix embedded images for some emails

Fix embedded images for some emails

---

lib/connection.js

Renamed fitler to filter

---

test/bounce-test.js
test/fixtures/bounces/zoho.eml

Added failing test for Zoho bounce emails

Added failing test for Zoho bounce emails

---

lib/bounce-detect.js
test/fixtures/bounces/zoho.eml

Detect Zoho bounce information

Detect Zoho bounce information

---

.github/workflows/deploy.yml
lib/account.js
lib/connection.js
lib/routes-ui.js
server.js
static/js/app.js
workers/api.js
workers/imap.js

Added flush endpoint to clear indexes from Redis and ElasticSearch for an account

Added flush endpoint

---

lib/account.js
workers/api.js

* global lock to decrease Redis scanning
* faster return
* Allow specifying syncFrom and notifyFrom

Flush imprevements

---

lib/mailbox.js
lib/routes-ui.js
lib/schemas.js
lib/tools.js
package.json
workers/api.js

Added new text option preProcessHtml to return message HTML compatible with embedding in other pages

preProcessHtml option

---

lib/account.js
lib/connection.js
lib/es.js
lib/mailbox.js
lib/threads.js
lib/webhooks.js
static/front/index.html

Document store inline attachments support

Document store inline attachments support

---

workers/api.js

Added API endpoints to show queue state and change it to paused/resume

Added API endpoints to show queue state and change it to paused/resume

---

lib/account.js
workers/api.js

Include account type in account listing and account info responses

Include account type in account listing and account info responses

---

workers/documents.js

Use tombstone marker to prevent indexing new emails that are already deleted

Prevent ElasticSearch indexing race conditions

---

lib/es.js
lib/mailbox.js
lib/routes-ui.js
lib/schemas.js
lib/settings.js
lib/webhooks.js
package.json
views/config/service.hbs
workers/api.js

Ther's a new option in Service->Labs section that allows to generate summaries for incoming emails using OpenAI

OpenAI Summary Generator

---

lib/connection.js
lib/routes-ui.js

Do not send a webhook for authenticationSuccess if nothing changed

Do not send a webhook for authenticationSuccess if nothing changed

---

lib/es.js
workers/documents.js

Fix race conditions when updating flags for emails in ElasticSearch

Fix race conditions when updating flags for emails in ElasticSearch

---

lib/connection.js

Increase attempt count for document queue jobs

Increase attempt count for document queue jobs

---

lib/es.js
lib/mailbox.js
lib/routes-ui.js
lib/schemas.js
package.json
views/config/webhooks.hbs

If `notifyCalendarEvents` setting is enabled, then include calendar event attachments as base64 encoded ical files for new message webhook payloads.
```json
{
"...": "...",
"data": {
"...": "...",
"calendarEvents": [
{
"eventId": "2rsjf307t2ckfpp3h3sf639ip7@google.com",
"attachment": "AAAAMQAACE8xLjM",
"method": "REQUEST",
"contentType": "text/calendar",
"encoding": "base64",
"content": "QkVHSU46VkNBTEVOREFSDQpQUk9ESUQ6LS8vR29vZ2xlIEluYy8vR29vZ2xlIENhbGVuZGFyIDcwLjkwNTQvL0VODQpWRVJTSU9OOjIuMA0KQ0FMU0NBTEU6R1JFR09SSUFODQpNRVRIT0Q6UkVRVUVTVA0KQkVHSU46VlRJTUVaT05FDQpUWklEOkV1cm9wZS9UYWxsaW5uDQpYLUxJQy1MT0NBVElPTjpFdXJvcGUvVGFsbGlubg0KQkVHSU46REFZTElHSFQNClRaT0ZGU0VURlJPTTorMDIwMA0KVFpPRkZTRVRUTzorMDMwMA0KVFpOQU1FOkVFU1QNCkRUU1RBUlQ6MTk3MDAzMjlUMDMwMDAwDQpSUlVMRTpGUkVRPVlFQVJMWTtCWU1PTlRIPTM7Q …
```

Fecth and include calendar events in webhooks

---

lib/account.js
workers/api.js

Added message query option webSafeHtml

Added message query option webSafeHtml

---

lib/account.js
lib/mailbox.js
lib/routes-ui.js
lib/schemas.js
views/config/webhooks.hbs

Added new option `notifyWebSafeHtml` - if set to true, then pre-processes HTML for `messsageNew`

Send web-safe webhook HTML

---

workers/api.js

Ensure documented values in account info output

Ensure documented values in account info output

---

lib/rate-limit.js
lib/routes-ui.js
server.js
static/css/app.css
views/layout/login.hbs
workers/api.js

Rate limit login and 2FA attempts

Rate limit login and 2FA attempts

---

lib/account.js
lib/es.js
lib/mailbox.js
lib/webhooks.js

If HTML pre-processing is enabled then cache the pre-processed value in document store

Cache pre-processed value in document store

---

lib/schemas.js
workers/api.js

Allow to set token specific rate limits

Allow to set token specific rate limits

---

lib/account.js
lib/connection.js
lib/oauth/gmail.js
lib/oauth/mail-ru.js
lib/oauth/outlook.js
lib/routes-ui.js
lib/tools.js
lib/webhooks.js
server.js
views/dashboard.hbs
views/internals/index.hbs
workers/api.js
workers/documents.js
workers/imap-proxy.js
workers/imap.js
workers/smtp.js
workers/submit.js
workers/webhooks.js

Include thread ID values in webhooks if document store is enabled

Include thread ID values in webhooks if document store is enabled

---

lib/routes-ui.js

Remember session after session update

Remember session after session update

---

lib/mailbox.js
package.json

Improved search for non-ascii characters

Improved search for non-ascii characters

---

lib/es.js
lib/mailbox.js
lib/routes-ui.js
lib/schemas.js
views/config/service.hbs

Use OpenAI API to assess risk for incoming emails

Use OpenAI API to assess risk for incoming emails

---

lib/connection.js
lib/get-raw-email.js
workers/api.js

Keep the BCC header in uploaded emails

Keep the BCC header in uploaded emails

---

lib/account.js
lib/db.js
lib/redis-url.js

Use date for sorting when listing unified search results

Use date for sorting when listing unified search results

---

lib/db.js
lib/redis-url.js

Show error in console if started manually and Redis connection fails

Show error in console if started manually and Redis connection fails

---

lib/es.js
package.json

Bumped email-ai-tools to get events extracted from email text

Bumped email-ai-tools to get events extracted from email text

---

lib/connection.js
lib/consts.js
lib/routes-ui.js
lib/schemas.js
package.json
views/config/service.hbs
workers/api.js

Allow to set the default delivery attempts count with a setting option

Default delivery attempts

---

lib/mailbox.js
lib/schemas.js

Include specialUse flag in message details response

Include specialUse flag in message details response

---

lib/account.js

Ensure specialUse and messageSpecialUse flags in a message info from the document store

Ensure specialUse and messageSpecialUse flags

---

lib/account.js

Document store special use

---

.gitignore
lib/connection.js
lib/imapproxy/imap-server.js
package.json

Adde boolean env EENGINE_DISABLE_COMPRESSION to disable IMAP compression

Adde boolean env EENGINE_DISABLE_COMPRESSION to disable IMAP compression

---

workers/api.js

Updated schema for nextAttempt value. Fixes #340

Update schema for nextAttempt value

---

lib/consts.js
lib/pre-process.js
lib/sub-script.js
lib/webhooks.js
static/css/app.css
static/js/evaluation-worker.js
views/config/document-store/pre-processing/edit.hbs
views/config/document-store/pre-processing/index.hbs
views/config/service.hbs
views/partials/editor_scope_info.hbs
views/partials/template_form.hbs
views/partials/webhook_form.hbs
views/partials/webhooks_editor_functions.hbs
views/templates/edit.hbs
views/templates/new.hbs
views/webhooks/webhook.hbs
workers/api.js

* allow to `await fetch()` in filter and mapping functions
* toggle fullscreen mode for code editors
* API endpoints for listing webhook routes

Async sub-scripts with fetch API

---

package.json

Process Gmail labels that start with a tilde

Process Gmail labels that start with a tilde

---

lib/connection.js
lib/db.js
lib/get-raw-email.js
server.js
workers/api.js

Allow uploading raw EML files

---

lib/autodetect-imap-settings.js
lib/connection.js
lib/mailbox.js
lib/tools.js

Previously EmailEngine failed to process messages if UIDVALIDITY for a folder was 0

Allow UIDVALIDITY=0

---

lib/connection.js

Fixed checking if the answered flags needs to be set or not

Fixed checking if the answered flags needs to be set or not

---

docker-compose.yml

Added IMAP proxy port to docker compose

Added IMAP proxy port to docker compose

---

workers/api.js

Ensure proxy IP as remote address if needed

Ensure proxy IP as remote address if needed

---

package.json

Delay IMAP responses on MS365 throttling

Delay IMAP responses on MS365 throttling

---

lib/routes-ui.js
lib/schemas.js
server.js
views/config/ai.hbs
views/config/document-store/pre-processing/edit.hbs

Added support for LLM options temperature and top_p

Added support for LLM options temperature and top_p
